name: Chunkpad

options:
  bundleIdPrefix: com.chunkpad
  deploymentTarget:
    macOS: "26.0"
  groupSortPosition: top
  createIntermediateGroups: true

packages:
  mlx-swift-lm:
    url: https://github.com/ml-explore/mlx-swift-lm
    from: "2.29.1"

settings:
  base:
    SWIFT_VERSION: "6.2"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    PRODUCT_NAME: Chunkpad

targets:
  Chunkpad:
    type: application
    platform: macOS
    sources:
      - Chunkpad
      - Vendor/CSQLiteVec
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chunkpad.app
        INFOPLIST_FILE: Chunkpad/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Chunkpad/Resources/Chunkpad.entitlements
        ENABLE_PREVIEWS: true
        OTHER_LDFLAGS: "-lsqlite3"
        GCC_PREPROCESSOR_DEFINITIONS:
          - SQLITE_CORE=1
    dependencies:
      - package: mlx-swift-lm
        products:
          - MLXEmbedders
